### ISSUE TITLE
ES module is annoying with bigger packages

### ISSUE THREAD

**Issue by EdJoPaTo** [sindresorhus/tsconfig#10]
Something that bugs me with the ES module change introduces in v1.0:

As soon as a package has more than one file it needs to import the other file.
Using `import {foo} from 'bar'` is valid TypeScript but `tsc` compiles it then into invalid JavaScript. This is a [bug of Typescript](https://github.com/Microsoft/TypeScript/issues/13422) with seemingly no intention to fix it or provide a flag to work around it.

The suggested solution is to write `import {foo} from 'bar.js'` in your TypeScript file which is dumb in my opinion. We import another TypeScript file and not JavaScript. `import {foo} from 'bar.ts'` is not supported here. Also the kinda default in the TypeScript world is to just omit the file extension (for example `got` does it too).

For small packages with just one file this isnt an issue but for everything else it seems weird. Personally I will just add `"module": "commonjs"` to my tsconfig for now and use v1.0 of this config.

I do not want to request a change here. I just want to tell about a hickup I experienced when upgrading to tsconfig v1.0 and maybe provide a place for others experiencing the same issue. Also I might miss something which helps with this issue? Please let me know. I would like to switch to ES modules.

**Comment by sindresorhus** [comment]
> import {foo} from 'bar'

I think you mean `import {foo} from './bar'`. `import {foo} from 'bar'` is totally valid.

**Comment by sindresorhus** [comment]
> Personally I will just add "module": "commonjs" to my tsconfig for now and use v1.0 of this config.

Beware that I and many other package maintainers are [moving all their packages to ESM next month](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77). CommonJS cannot easily import ESM.

Long-term, I think you'll just have to learn to live with the `.js` extension.
