### ISSUE TITLE
Do not skipLibCheck

### ISSUE THREAD

**Issue by fregante** [sindresorhus/tsconfig#15]
I'm currently looking into using `d.ts` files as a way to declare some types using imports from libraries without risking to import the libraries themselves.

Example:

```ts
// my.d.ts
import eslint from "eslint"

export type ESLint = typeof esIint;
```

Did you catch that? TypeScript didn't. The `.d.ts` file above "passes" `tsc` validation but `typeof eslint` is spelled as `typeof ESIINT`.

Use `skipLibCheck: false` and it works:

<img width="454" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/132013970-2542bbe4-5c8e-47bc-96df-b10bf1852aad.png">

**Comment by sindresorhus** [comment]
But with lib skip off, checking becomes much slower... Is there any way to only check local files and ignore other packages? If not, might be worth opening a TS issue.

**Comment by voxpelli** [comment]
> Skip type checking of declaration files.

I had interpreted / remembered this option as meaning that types within dependencies weren't checked to be correct, only ones defined in ones own project, but the quote above is from the docs, so I agree, it's not good to have. See: https://www.typescriptlang.org/tsconfig#skipLibCheck

**Comment by fregante** [comment]
Yeah I suppose the intended use of d.ts is to share types across libraries rather than locally, hence the skip LIB check.

In the past I enabled this flag (in an attempt) to fix some node_modules issues too, but I don't remember if it was effective — that means that disabling it might bring those back (however I disabled it in a couple of large projects without issue)

**Comment by voxpelli** [comment]
So – ran into this again in `type-fest`: https://github.com/sindresorhus/type-fest/pull/785

Whenever one handcrafts `.d.ts` files one should really keep `skipLibCheck` turned off.

**Comment by voxpelli** [comment]
Another victim of `skipLibCheck`: https://github.com/octet-stream/form-data-encoder/issues/24

Inadvertently makes `got` require `skipLibCheck` or `dom` types

Would have been caught if this config would disable `skipLibCheck`

(I’ll report a proper issue in `got` later on, for now just want to document it as yet another `skipLibCheck` problem)
