### ISSUE TITLE
Dropping `moduleResolution: node` breaks any node_modules imports

### ISSUE THREAD

**Issue by fregante** [sindresorhus/tsconfig#18]
Continuing from https://github.com/sindresorhus/tsconfig/commit/44a7e4c236f5539418e3f45a0b99386ad7631be5#r74826372

> This seems to break all of my module imports. 🤔  Why was it removed?
> 
> <img width="484" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/170854269-9b9ebd55-a6d7-4ff0-a9db-419a452fa255.png">
> 
> The "classic" resolution does not look inside node_modules
> 
> https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies
> 

This does work:

```js
"moduleResolution": "node16"
```

**Comment by sindresorhus** [comment]
> https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#ecmascript-module-support-in-node-js does not mention that `moduleResolution` is required and I assumed it would be smart enough to match it when `"module": "node16",`.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/tsconfig/releases/tag/v3.0.1

**Comment by fregante** [comment]
> I assumed it would be smart enough to match it when `"module": "node16",`.

That appears to be what TS contributors think too:

https://github.com/microsoft/TypeScript/issues/49291#issuecomment-1142150617

> unless you actually want a differen `"moduleResolution'` value there's not really any reason to specify it when using `"module"`.

… yet here we are 😅

**Comment by kidonng** [comment]
From a quick glance at [TS codebase](https://github.com/microsoft/TypeScript/blob/549e61d0af1ba885be29d69f341e7d3a00686071/src/compiler/utilities.ts#L6369-L6388) it does seem `moduleResolution` _should_ choose a default based on `module` though 🤔 this could potentially be a TS bug?
