### ISSUE TITLE
`module: node16` + `moduleResolution: node` generates CommonJS file

### ISSUE THREAD

**Issue by fregante** [sindresorhus/tsconfig#21]
🥲 

## Repro

```sh
npm install @sindresorhus/tsconfig typescript
echo 'export default 42'> index.ts
echo '{"extends": "@sindresorhus/tsconfig", "files": ["index.ts"]}' > tsconfig.json
npx tsc
cat index.js
cat package.json
```

### Output 

```sh
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = 42;
```

```
{
  "dependencies": {
    "@sindresorhus/tsconfig": "^3.0.1",
    "typescript": "^4.7.4"
  }
}
```
tsconfig v3 basically:

![image](https://user-images.githubusercontent.com/1402241/175340539-bed7b5f3-2e78-48ee-a370-6c67f93c4fc2.gif)

**Comment by fregante** [comment]
I thought it might just follow the `type` field in package.json, but that doesn't seem to be the case. It generates CJS even with `type:module`

**Comment by sindresorhus** [comment]
I'm using this config here: https://github.com/sindresorhus/is/blob/main/tsconfig.json And it correctly generates ESM.

**Comment by sindresorhus** [comment]
Yes, I only get CJS with your repro if I don't specify `"type": "module"`.

**Comment by fregante** [comment]
In my case I also had `type: module` **and** `moduleResolution: node`. Without that I got:

```ts
index.ts:1:34 - error TS2307: Cannot find module 'typed-query-selector/parser' or its corresponding type declarations.

1 import type {ParseSelector} from 'typed-query-selector/parser';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

`moduleResolution: node` cannot be used in conjunction with `module: node16`. Setting `module: es2022` works but I ended up "fixing" the import instead:

```diff
- import type {ParseSelector} from 'typed-query-selector/parser';
+ import type {ParseSelector} from 'typed-query-selector/parser.d.js';
```
