### ISSUE TITLE
Publish new major version to NPM

### ISSUE THREAD

**Issue by bjornstar** [sindresorhus/tsconfig#23]
It looks like [the changes made 4 months ago](https://github.com/sindresorhus/tsconfig/commit/3ae0110ab3f1db30f4009b56cded744aa5218b71) have not been published to NPM. Is there a chance we can get them published with a new major version so that we can use the new defaults in other projects?

(I noticed this when using `Intl.ListFormat` in https://github.com/sindresorhus/is/pull/193)

**Comment by EdJoPaTo** [comment]
With Node.js 16 out of LTS soon it might be also a good idea to just bump to Node.js ≥ 18. One less breaking change.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/tsconfig/releases/tag/v4.0.0

**Comment by sindresorhus** [comment]
> With Node.js 16 end of life soon (2023-09-11) it might be also a good idea to just bump to Node.js ≥ 18. One less breaking change release.

Interesting. Usually, it's in April. It doesn't make sense to require Node.js 18 yet. I generally strictly follow the release schedule and only do it afterwards.

**Comment by EdJoPaTo** [comment]
> Interesting. Usually, it's in April.

It was pulled ahead because of the OpenSSL deprecation which Node.js 16 also depends upon. They wouldn't be able to fix bugs with that so they can't support their LTS claim.
https://nodejs.dev/en/blog/announcements/nodejs16-eol/
