### ISSUE TITLE
`outDir` issue fixed in TS 5.5?

### ISSUE THREAD

**Issue by fregante** [sindresorhus/tsconfig#27]
- Release: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-configdir-template-variable-for-configuration-files
- Report: https://github.com/Microsoft/TypeScript/issues/29172
- Code: https://github.com/sindresorhus/tsconfig/blob/7aea33c6fd9224b7c6ae3b652bd884904ab1a800/tsconfig.json#L3-L4

**Comment by fregante** [comment]
Uh I think this is technically a breaking change. If they were expecting files in /dist, now they're not found anymore.

**Comment by sindresorhus** [comment]
It does not override what you have defined in your own config. `outDir` has no value by default.

**Comment by fregante** [comment]
Typescript will output the files somewhere whether the key is set or not. If the user didn't set it (as is common for me), this minor version will now output it somewhere else until I update my config. 

If unnoticed, this can lead to published packages that don't have the files expected.

**Comment by fregante** [comment]
> If not specified, .js files will be emitted in the same directory as the .ts files they were generated from:

The default value is `./` and this changes it to `./distribution`

**Comment by sindresorhus** [comment]
Resolved

**Comment by fregante** [comment]
v6 forces 5.4 users to set `outDir`. If they don't, the output will be hidden from them as it will be in the literal folder:

```
./node_modules/@sindresorhus/tsconfig/${configPath}/distribution
```

Instead of the previous:

```
./
```

I'd say either mention "minimum TS v5.5" or "set your own outDir if you're still on 5.4". 

I saw this first-hand because `tsc` was not producing any output and I had to figure this out via `tsc --build --verbose`

**Comment by sindresorhus** [comment]
Updated release notes: https://github.com/sindresorhus/tsconfig/releases/tag/v6.0.0
