### ISSUE TITLE
`useDefineForClassFields` produces broken code

### ISSUE THREAD

**Issue by fregante** [sindresorhus/tsconfig#7]
I can't reproduce online but here's the [repro](https://github.com/sindresorhus/tsconfig/files/3948927/repo.zip). 

Bug: https://github.com/microsoft/TypeScript/issues/35590
Also related: https://github.com/microsoft/TypeScript/issues/35426

## Input
```json
{
	"compilerOptions": {
		"target": "es2017",
		"useDefineForClassFields": true
	}
}
```
```ts
export default class {
	private _form!: HTMLFormElement;
	constructor() {
		console.log(this._form)
	}
}
```

## Output

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
class default_1 {
    constructor() {
        Object.defineProperty(this, "_form", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: _form ///////////////// WRONG
        });
        console.log(this._form);
    }
}
exports.default = default_1;
```

Online that value is correctly set to `void 0` instead of an undefined variable.

**Comment by fatcerberus** [comment]
> I can't reproduce online

The bug was introduced in 3.7.3.  The Playground is currently on 3.7.2; you can reproduce if you switch the Playground to Nightly.

**Comment by sindresorhus** [comment]
Ugh. Yeah, let's just disable it for now.
