### ISSUE TITLE
Add esModuleInterop?

### ISSUE THREAD

**Issue by voxpelli** [sindresorhus/tsconfig#8]
See https://github.com/microsoft/TypeScript/issues/41139

As stated in https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop:

> We highly recommend applying it both to new and existing projects.

Should make TS and ESM work better together.

**Comment by sindresorhus** [comment]
Is it really needed when the TS package is native ESM? I remember using that flag in the past and it caused a lot of problems.

**Comment by voxpelli** [comment]
It’s probably primarily needed when importing a CJS module or exporting as a CJS module, but overall it seems like it’s the ESM setup that the TS team intends to be its default but for extreme backwards compatibility reasons doesn’t dare to change into the default

**Comment by EdJoPaTo** [comment]
Taking a look on the [tsconfig recommended bases](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases) is interesting here.

The [baseline](https://www.npmjs.com/package/@tsconfig/recommended) and [NodeJS 12 version](https://www.npmjs.com/package/@tsconfig/node12) both include `esModuleInterop`. (Interestingly the NodeJS 12 version has some libs included which are not included in this one. But thats a different topic)

When taking a look on the [deno base](https://www.npmjs.com/package/@tsconfig/deno) `esModuleInterop` is not enabled. I am curious why.

Personally: As soon as one module has `esModuleInterop` enabled all the packages that depend on that also have to enable that. As I do not want to force that decision on the users I do not enable that in my modules.

**Comment by voxpelli** [comment]
Does anyone know the TypeScript teams intention here? I’ve tried to figure it out at it all pointed me to `esModuleInterop` being the option they promote

**Comment by voxpelli** [comment]
An [example from `read-pkg`](https://github.com/sindresorhus/read-pkg/compare/v5.2.0...v6.0.0):

[![Skärmavbild 2021-03-29 kl  09 28 07](https://user-images.githubusercontent.com/34457/112801415-274d1780-9071-11eb-87a9-1aa7ac5482e2.png)](https://github.com/sindresorhus/read-pkg/blob/55549f35b4fafbde90de4ca8b2136ad1d4d4dcb5/index.js#L4)

[![Skärmavbild 2021-03-29 kl  09 28 15](https://user-images.githubusercontent.com/34457/112801395-21efcd00-9071-11eb-9977-f6d4b2e8a17f.png)](https://github.com/sindresorhus/read-pkg/blob/55549f35b4fafbde90de4ca8b2136ad1d4d4dcb5/index.d.ts#L2)

They should both really be the same, but that would probably require all users of the types to also adopt `esModuleInterop` 🤔

**Comment by fregante** [comment]
esModuleInterop breaks exports node usage when importing your module. In short it lets you `import` a CJS package but once you publish that code on npm then you get code that doesn't run. 

The flag should probably only be used in projects that are not meant to be imported or uploaded to npm.

**Comment by voxpelli** [comment]
> By default (with esModuleInterop false or not set) TypeScript treats CommonJS/AMD/UMD modules similar to ES6 modules. In doing this, there are two parts in particular which turned out to be flawed assumptions:

From: https://www.typescriptlang.org/tsconfig#esModuleInterop

@fregante It's still the recommended option by the TypeScript team and its still as far as I can tell their intended fix for becoming more interoperable with the ESM landscape.

Is there a bug tracking the behavior you are mentioning? If not, can you mentioning it in https://github.com/microsoft/TypeScript/issues/41139 and/or a dedicated issue?

The current limbo situation of `esModuleInterop` is really undesireable :/

**Comment by Caglar1881** [comment]
#11

**Comment by Caglar1881** [comment]
> [#11 ](https://github.com/sindresorhus/tsconfig/pull/11) #8

**Comment by fregante** [comment]
Since this is still open, I want to reiterated that this is likely still a bad idea as a default.

My rule for this:

- `esModuleInterop: true` for apps (final user)
- `esModuleInterop: false` by libraries/modules (npm users)

`true` is useful in apps (webpack) because it simplifies usage of any package. The problem is that it breaks the output of libraries because it lets you import modules _the wrong way._ That wrong import will appear in `tsc`’s output as well, making it too easy to create non-importable npm packages, even if they pass the local tests.

I think more context can be found in:

- https://github.com/sindresorhus/mem/issues/31
- https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default

**Comment by voxpelli** [comment]
To make things even more interesting, TypeScript 4.5 looks likely to add  two new [`'module'`](https://www.typescriptlang.org/tsconfig#module) types: `node12` and `nodenext`. See https://github.com/microsoft/TypeScript/pull/44501

Purpose of those are to eg. ensure that `await import()` doesn't get transpiled into `require()` when TypeScript is transpiled to CJS, thus enabling CJS-based TS projects to actually use ESM modules.

And most relevant to this thread:

> both options imply esModuleInterop

**Comment by fregante** [comment]
> ensure that `await import()` doesn't get transpiled into `require()`

🎉 


> And most relevant to this thread:
> 
> > both options imply esModuleInterop

😰 That seems to contradict the first part.

Does that mean that the information I posted is outdated? I think node was exactly the problem back then. Maybe the issue was exactly CJS transpilation, which isn't the default in this configuration 🤔

**Comment by voxpelli** [comment]
I know that @bmeck asked a possibly relevant question over there (https://github.com/microsoft/TypeScript/pull/44501#issuecomment-904702898) referencing a comment he made to my very issue that I started our thread here with

**Comment by voxpelli** [comment]
> To make things even more interesting, TypeScript 4.5 looks likely to add two new [`'module'`](https://www.typescriptlang.org/tsconfig#module) types: `node12` and `nodenext`. See [microsoft/TypeScript#44501](https://github.com/microsoft/TypeScript/pull/44501)
> 
> > both options imply esModuleInterop

This shipped and since this config now uses `"module": "node16"` that means that `esModuleInterop` is now on in this config, see: https://github.com/microsoft/TypeScript/issues/41139#issuecomment-1296280988

Actual code in TS for it: https://github.com/microsoft/TypeScript/blob/2bcfed01f3458996e71ce37af43e3495cb7e4950/src/compiler/utilities.ts#L6428-L6438

**Comment by fregante** [comment]
I think this is fine because the "node16" config I think is annoyingly strict so this kind of interop doesn't really cause issues. 👍
